server:
  port: 8080

logging:
  level:
    root: WARN
    org:
      springframework:
        web: INFO
        security: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456aaa
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mvc:
    static-path-pattern: /**